AllCops:
  Exclude:
    - Rakefile
    - bin/**/*
    - config.ru
    - config/**/*
    - db/**/*
    - lib/tasks/**/*
    - node_modules/**/*
    - script/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - vendor/**/*

Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Rails:
  Enabled: true

StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

